// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-r8CBPsVkQHgn-hz9Pr-3DQe2LfheU4g',
    appId: '1:760766658712:web:49e02447e45f443e8bb8ed',
    messagingSenderId: '760766658712',
    projectId: 'chemai-79081',
    authDomain: 'chemai-79081.firebaseapp.com',
    storageBucket: 'chemai-79081.firebasestorage.app',
    measurementId: 'G-1E55HSJ3QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCotMuxJxwIztk7Lp3nvqHihkkbn8yzX7o',
    appId: '1:760766658712:android:8c30cf5167f62a648bb8ed',
    messagingSenderId: '760766658712',
    projectId: 'chemai-79081',
    storageBucket: 'chemai-79081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2z_OYRQxE5MsMG7RVxlBaDrCd_wtjrzI',
    appId: '1:760766658712:ios:3113ecda9c4b38488bb8ed',
    messagingSenderId: '760766658712',
    projectId: 'chemai-79081',
    storageBucket: 'chemai-79081.firebasestorage.app',
    iosBundleId: 'com.example.chemAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2z_OYRQxE5MsMG7RVxlBaDrCd_wtjrzI',
    appId: '1:760766658712:ios:3113ecda9c4b38488bb8ed',
    messagingSenderId: '760766658712',
    projectId: 'chemai-79081',
    storageBucket: 'chemai-79081.firebasestorage.app',
    iosBundleId: 'com.example.chemAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-r8CBPsVkQHgn-hz9Pr-3DQe2LfheU4g',
    appId: '1:760766658712:web:cb016fc0f3c2216d8bb8ed',
    messagingSenderId: '760766658712',
    projectId: 'chemai-79081',
    authDomain: 'chemai-79081.firebaseapp.com',
    storageBucket: 'chemai-79081.firebasestorage.app',
    measurementId: 'G-1P78RQ3WGY',
  );
}
